# Generated by Django 3.1.4 on 2020-12-07 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MJAPI.contact')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryPartner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('picture', models.ImageField(upload_to='pictures/delivery-staff/')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MJAPI.contact')),
            ],
        ),
        migrations.CreateModel(
            name='Retailer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopName', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('logo', models.ImageField(upload_to='pictures/retailers/')),
                ('address', models.CharField(max_length=100)),
                ('available', models.BooleanField()),
                ('SIRET', models.CharField(max_length=100)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MJAPI.contact')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('pricingModel', models.CharField(max_length=50)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('prepTime', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='MJAPI.category')),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='MJAPI.retailer')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('shippedAt', models.DateTimeField()),
                ('deliveredAt', models.DateTimeField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='MJAPI.customer')),
                ('deliveryPartner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='MJAPI.deliverypartner')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='MJAPI.product')),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='MJAPI.retailer')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='favoriteShops',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='MJAPI.retailer'),
        ),
    ]
