# Generated by Django 3.1.4 on 2020-12-12 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MJAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='retailer',
            options={'verbose_name': 'Retailer', 'verbose_name_plural': 'Retailers'},
        ),
    ]
