# Generated by Django 3.1.4 on 2020-12-13 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MJAPI', '0005_auto_20201212_1854'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliverypartner',
            options={'verbose_name': 'Delivery Partner', 'verbose_name_plural': 'Delivery Partners'},
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='firstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='lastName',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='favoriteShops',
            new_name='favorite_shops',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='prepTime',
            new_name='prep_time',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='pricingModel',
            new_name='pricing_model',
        ),
        migrations.RenameField(
            model_name='retailer',
            old_name='shopName',
            new_name='shop_name',
        ),
        migrations.AddField(
            model_name='customer',
            name='favorite_products',
            field=models.ManyToManyField(to='MJAPI.Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MJAPI.category'),
        ),
    ]
